spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://m60mxazb4g6sb4nn.chr7pe7iynqr.eu-west-1.rds.amazonaws.com:3306/svbfrojp9k9nk238
spring.datasource.username=z6nzwx4qtbmte6ar
spring.datasource.password=b7qbbg6kzesdg5ur
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# App Properties
dummy.app.jwtSecret=DummySecretKey
dummy.app.jwtExpirationMs=86400000
